name = "cereka-docs"
compatibility_date = "2026-05-08"

pages_build_output_dir = "docs/book"
pages_build_command = "mdbook build docs"

[env.production]
routes = [{ pattern = "docs.cereka.dev", custom_domain = true }]
